version: '3.4'

networks:
  k6:
  grafana:


services:
  
  k6:
    image: grafana/k6:latest
    tty: true   
    networks:
      - k6
    working_dir: /app
    environment:
      - K6_WEB_DASHBOARD=true
    volumes:
      - ./scripts:/app
      - ./report:/report
    ports:
      - "6565:6565"
      - "5665:5665"
    # deploy:
    #     resources:
    #         limits:
    #           cpus: '1'
    #           memory: 500M
    #         reservations:
    #           cpus: '0.20'
    #           memory: 15M

  k6-test-api:
    image: chankx/k6api
    command: sh -c "python project/manage.py makemigrations && python project/manage.py migrate && python project/manage.py loaddata project/fixtures/initial.json && python project/manage.py runserver 0.0.0.0:8000"
    container_name: k6testapi
    working_dir: /srv/test-api.k6.io
    volumes:
      - ./test-api.k6.io:/srv/test-api.k6.io
    networks:
      - k6
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT_NAME=dev
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300m
        reservations:
          cpus: '0.20'
          memory: 250M

  httpbin:
    container_name: httpbin
    image: kennethreitz/httpbin
    networks:
      - k6
    restart: always
    ports:
      - "8801:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 60m
        reservations:
          cpus: '0.20'
          memory: 15M
  srv01:
    container_name: app-srv01
    image: chankx/demo-loadtest-app:latest
    networks:
      - k6
    restart: always
    ports:
      - "3001:3000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 150m
        reservations:
          cpus: '0.20'
          memory: 15M
